version: 2
jobs:
  build:
    working_directory: ~/riemann_generic
    docker:
      - image: circleci/clojure:lein-2.7.1
    environment:
      LEIN_ROOT: "true"
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: riemann-generic-{{ checksum "project.clj" }}
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
          key: riemann-generic-{{ checksum "project.clj" }}
      - run: lein test